- app_name: Rest
  log_files: ["/data/stellar3/stellar_3.1.0/logs/error.log"]
  pre_match: "2006.01.02"
  must: []
  must_not: []
- app_name: User-message
  log_files: ["/data/stellar3/ucaas-stellar3-user-message/logs/error.log"]
  pre_match: "2006.01.02"
  must: ["abc", "d"]
  must_not: []